with-expecter: true
dir: "mocks/{{.PackagePath}}"
filename: "{{.InterfaceName}}.go"
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
packages:
  github.com/wisp-trading/wisp/pkg:
    config:
      recursive: true
      all: true
