// Code generated by mockery v2.53.5. DO NOT EDIT.

package live

import (
	context "context"

	config "github.com/wisp-trading/sdk/pkg/types/config"

	live "github.com/wisp-trading/wisp/pkg/live"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// InstanceManager is an autogenerated mock type for the InstanceManager type
type InstanceManager struct {
	mock.Mock
}

type InstanceManager_Expecter struct {
	mock *mock.Mock
}

func (_m *InstanceManager) EXPECT() *InstanceManager_Expecter {
	return &InstanceManager_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: instanceID
func (_m *InstanceManager) Get(instanceID string) (*live.Instance, error) {
	ret := _m.Called(instanceID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *live.Instance
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*live.Instance, error)); ok {
		return rf(instanceID)
	}
	if rf, ok := ret.Get(0).(func(string) *live.Instance); ok {
		r0 = rf(instanceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*live.Instance)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(instanceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InstanceManager_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type InstanceManager_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - instanceID string
func (_e *InstanceManager_Expecter) Get(instanceID interface{}) *InstanceManager_Get_Call {
	return &InstanceManager_Get_Call{Call: _e.mock.On("Get", instanceID)}
}

func (_c *InstanceManager_Get_Call) Run(run func(instanceID string)) *InstanceManager_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *InstanceManager_Get_Call) Return(_a0 *live.Instance, _a1 error) *InstanceManager_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InstanceManager_Get_Call) RunAndReturn(run func(string) (*live.Instance, error)) *InstanceManager_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Kill provides a mock function with given fields: instanceID
func (_m *InstanceManager) Kill(instanceID string) error {
	ret := _m.Called(instanceID)

	if len(ret) == 0 {
		panic("no return value specified for Kill")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(instanceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InstanceManager_Kill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kill'
type InstanceManager_Kill_Call struct {
	*mock.Call
}

// Kill is a helper method to define mock.On call
//   - instanceID string
func (_e *InstanceManager_Expecter) Kill(instanceID interface{}) *InstanceManager_Kill_Call {
	return &InstanceManager_Kill_Call{Call: _e.mock.On("Kill", instanceID)}
}

func (_c *InstanceManager_Kill_Call) Run(run func(instanceID string)) *InstanceManager_Kill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *InstanceManager_Kill_Call) Return(_a0 error) *InstanceManager_Kill_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InstanceManager_Kill_Call) RunAndReturn(run func(string) error) *InstanceManager_Kill_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: status
func (_m *InstanceManager) List(status live.InstanceStatus) ([]*live.Instance, error) {
	ret := _m.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*live.Instance
	var r1 error
	if rf, ok := ret.Get(0).(func(live.InstanceStatus) ([]*live.Instance, error)); ok {
		return rf(status)
	}
	if rf, ok := ret.Get(0).(func(live.InstanceStatus) []*live.Instance); ok {
		r0 = rf(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*live.Instance)
		}
	}

	if rf, ok := ret.Get(1).(func(live.InstanceStatus) error); ok {
		r1 = rf(status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InstanceManager_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type InstanceManager_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - status live.InstanceStatus
func (_e *InstanceManager_Expecter) List(status interface{}) *InstanceManager_List_Call {
	return &InstanceManager_List_Call{Call: _e.mock.On("List", status)}
}

func (_c *InstanceManager_List_Call) Run(run func(status live.InstanceStatus)) *InstanceManager_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(live.InstanceStatus))
	})
	return _c
}

func (_c *InstanceManager_List_Call) Return(_a0 []*live.Instance, _a1 error) *InstanceManager_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InstanceManager_List_Call) RunAndReturn(run func(live.InstanceStatus) ([]*live.Instance, error)) *InstanceManager_List_Call {
	_c.Call.Return(run)
	return _c
}

// LoadRunning provides a mock function with given fields: ctx
func (_m *InstanceManager) LoadRunning(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadRunning")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InstanceManager_LoadRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadRunning'
type InstanceManager_LoadRunning_Call struct {
	*mock.Call
}

// LoadRunning is a helper method to define mock.On call
//   - ctx context.Context
func (_e *InstanceManager_Expecter) LoadRunning(ctx interface{}) *InstanceManager_LoadRunning_Call {
	return &InstanceManager_LoadRunning_Call{Call: _e.mock.On("LoadRunning", ctx)}
}

func (_c *InstanceManager_LoadRunning_Call) Run(run func(ctx context.Context)) *InstanceManager_LoadRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *InstanceManager_LoadRunning_Call) Return(_a0 error) *InstanceManager_LoadRunning_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InstanceManager_LoadRunning_Call) RunAndReturn(run func(context.Context) error) *InstanceManager_LoadRunning_Call {
	_c.Call.Return(run)
	return _c
}

// SaveState provides a mock function with no fields
func (_m *InstanceManager) SaveState() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SaveState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InstanceManager_SaveState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveState'
type InstanceManager_SaveState_Call struct {
	*mock.Call
}

// SaveState is a helper method to define mock.On call
func (_e *InstanceManager_Expecter) SaveState() *InstanceManager_SaveState_Call {
	return &InstanceManager_SaveState_Call{Call: _e.mock.On("SaveState")}
}

func (_c *InstanceManager_SaveState_Call) Run(run func()) *InstanceManager_SaveState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InstanceManager_SaveState_Call) Return(_a0 error) *InstanceManager_SaveState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InstanceManager_SaveState_Call) RunAndReturn(run func() error) *InstanceManager_SaveState_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields: ctx, timeout
func (_m *InstanceManager) Shutdown(ctx context.Context, timeout time.Duration) error {
	ret := _m.Called(ctx, timeout)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) error); ok {
		r0 = rf(ctx, timeout)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InstanceManager_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type InstanceManager_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
//   - timeout time.Duration
func (_e *InstanceManager_Expecter) Shutdown(ctx interface{}, timeout interface{}) *InstanceManager_Shutdown_Call {
	return &InstanceManager_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx, timeout)}
}

func (_c *InstanceManager_Shutdown_Call) Run(run func(ctx context.Context, timeout time.Duration)) *InstanceManager_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Duration))
	})
	return _c
}

func (_c *InstanceManager_Shutdown_Call) Return(_a0 error) *InstanceManager_Shutdown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InstanceManager_Shutdown_Call) RunAndReturn(run func(context.Context, time.Duration) error) *InstanceManager_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx, strategy, frameworkRoot
func (_m *InstanceManager) Start(ctx context.Context, strategy *config.Strategy, frameworkRoot string) (*live.Instance, error) {
	ret := _m.Called(ctx, strategy, frameworkRoot)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 *live.Instance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *config.Strategy, string) (*live.Instance, error)); ok {
		return rf(ctx, strategy, frameworkRoot)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *config.Strategy, string) *live.Instance); ok {
		r0 = rf(ctx, strategy, frameworkRoot)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*live.Instance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *config.Strategy, string) error); ok {
		r1 = rf(ctx, strategy, frameworkRoot)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InstanceManager_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type InstanceManager_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - strategy *config.Strategy
//   - frameworkRoot string
func (_e *InstanceManager_Expecter) Start(ctx interface{}, strategy interface{}, frameworkRoot interface{}) *InstanceManager_Start_Call {
	return &InstanceManager_Start_Call{Call: _e.mock.On("Start", ctx, strategy, frameworkRoot)}
}

func (_c *InstanceManager_Start_Call) Run(run func(ctx context.Context, strategy *config.Strategy, frameworkRoot string)) *InstanceManager_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*config.Strategy), args[2].(string))
	})
	return _c
}

func (_c *InstanceManager_Start_Call) Return(_a0 *live.Instance, _a1 error) *InstanceManager_Start_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InstanceManager_Start_Call) RunAndReturn(run func(context.Context, *config.Strategy, string) (*live.Instance, error)) *InstanceManager_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with given fields: instanceID
func (_m *InstanceManager) Stop(instanceID string) error {
	ret := _m.Called(instanceID)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(instanceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InstanceManager_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type InstanceManager_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - instanceID string
func (_e *InstanceManager_Expecter) Stop(instanceID interface{}) *InstanceManager_Stop_Call {
	return &InstanceManager_Stop_Call{Call: _e.mock.On("Stop", instanceID)}
}

func (_c *InstanceManager_Stop_Call) Run(run func(instanceID string)) *InstanceManager_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *InstanceManager_Stop_Call) Return(_a0 error) *InstanceManager_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InstanceManager_Stop_Call) RunAndReturn(run func(string) error) *InstanceManager_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// StopByStrategyName provides a mock function with given fields: strategyName
func (_m *InstanceManager) StopByStrategyName(strategyName string) error {
	ret := _m.Called(strategyName)

	if len(ret) == 0 {
		panic("no return value specified for StopByStrategyName")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(strategyName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InstanceManager_StopByStrategyName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopByStrategyName'
type InstanceManager_StopByStrategyName_Call struct {
	*mock.Call
}

// StopByStrategyName is a helper method to define mock.On call
//   - strategyName string
func (_e *InstanceManager_Expecter) StopByStrategyName(strategyName interface{}) *InstanceManager_StopByStrategyName_Call {
	return &InstanceManager_StopByStrategyName_Call{Call: _e.mock.On("StopByStrategyName", strategyName)}
}

func (_c *InstanceManager_StopByStrategyName_Call) Run(run func(strategyName string)) *InstanceManager_StopByStrategyName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *InstanceManager_StopByStrategyName_Call) Return(_a0 error) *InstanceManager_StopByStrategyName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InstanceManager_StopByStrategyName_Call) RunAndReturn(run func(string) error) *InstanceManager_StopByStrategyName_Call {
	_c.Call.Return(run)
	return _c
}

// NewInstanceManager creates a new instance of InstanceManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInstanceManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *InstanceManager {
	mock := &InstanceManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
