// Code generated by mockery v2.53.5. DO NOT EDIT.

package live

import (
	context "context"

	config "github.com/wisp-trading/sdk/pkg/types/config"

	exec "os/exec"

	live "github.com/wisp-trading/wisp/pkg/live"

	mock "github.com/stretchr/testify/mock"
)

// ProcessSpawner is an autogenerated mock type for the ProcessSpawner type
type ProcessSpawner struct {
	mock.Mock
}

type ProcessSpawner_Expecter struct {
	mock *mock.Mock
}

func (_m *ProcessSpawner) EXPECT() *ProcessSpawner_Expecter {
	return &ProcessSpawner_Expecter{mock: &_m.Mock}
}

// AttachMonitor provides a mock function with given fields: instance
func (_m *ProcessSpawner) AttachMonitor(instance *live.Instance) error {
	ret := _m.Called(instance)

	if len(ret) == 0 {
		panic("no return value specified for AttachMonitor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*live.Instance) error); ok {
		r0 = rf(instance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessSpawner_AttachMonitor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachMonitor'
type ProcessSpawner_AttachMonitor_Call struct {
	*mock.Call
}

// AttachMonitor is a helper method to define mock.On call
//   - instance *live.Instance
func (_e *ProcessSpawner_Expecter) AttachMonitor(instance interface{}) *ProcessSpawner_AttachMonitor_Call {
	return &ProcessSpawner_AttachMonitor_Call{Call: _e.mock.On("AttachMonitor", instance)}
}

func (_c *ProcessSpawner_AttachMonitor_Call) Run(run func(instance *live.Instance)) *ProcessSpawner_AttachMonitor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*live.Instance))
	})
	return _c
}

func (_c *ProcessSpawner_AttachMonitor_Call) Return(_a0 error) *ProcessSpawner_AttachMonitor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProcessSpawner_AttachMonitor_Call) RunAndReturn(run func(*live.Instance) error) *ProcessSpawner_AttachMonitor_Call {
	_c.Call.Return(run)
	return _c
}

// Spawn provides a mock function with given fields: ctx, strategy
func (_m *ProcessSpawner) Spawn(ctx context.Context, strategy *config.Strategy) (*exec.Cmd, error) {
	ret := _m.Called(ctx, strategy)

	if len(ret) == 0 {
		panic("no return value specified for Spawn")
	}

	var r0 *exec.Cmd
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *config.Strategy) (*exec.Cmd, error)); ok {
		return rf(ctx, strategy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *config.Strategy) *exec.Cmd); ok {
		r0 = rf(ctx, strategy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exec.Cmd)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *config.Strategy) error); ok {
		r1 = rf(ctx, strategy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessSpawner_Spawn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Spawn'
type ProcessSpawner_Spawn_Call struct {
	*mock.Call
}

// Spawn is a helper method to define mock.On call
//   - ctx context.Context
//   - strategy *config.Strategy
func (_e *ProcessSpawner_Expecter) Spawn(ctx interface{}, strategy interface{}) *ProcessSpawner_Spawn_Call {
	return &ProcessSpawner_Spawn_Call{Call: _e.mock.On("Spawn", ctx, strategy)}
}

func (_c *ProcessSpawner_Spawn_Call) Run(run func(ctx context.Context, strategy *config.Strategy)) *ProcessSpawner_Spawn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*config.Strategy))
	})
	return _c
}

func (_c *ProcessSpawner_Spawn_Call) Return(_a0 *exec.Cmd, _a1 error) *ProcessSpawner_Spawn_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProcessSpawner_Spawn_Call) RunAndReturn(run func(context.Context, *config.Strategy) (*exec.Cmd, error)) *ProcessSpawner_Spawn_Call {
	_c.Call.Return(run)
	return _c
}

// NewProcessSpawner creates a new instance of ProcessSpawner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProcessSpawner(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProcessSpawner {
	mock := &ProcessSpawner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
