// Code generated by mockery v2.53.5. DO NOT EDIT.

package live

import mock "github.com/stretchr/testify/mock"

// Runtime is an autogenerated mock type for the Runtime type
type Runtime struct {
	mock.Mock
}

type Runtime_Expecter struct {
	mock *mock.Mock
}

func (_m *Runtime) EXPECT() *Runtime_Expecter {
	return &Runtime_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: strategyDir
func (_m *Runtime) Run(strategyDir string) error {
	ret := _m.Called(strategyDir)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(strategyDir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Runtime_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Runtime_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - strategyDir string
func (_e *Runtime_Expecter) Run(strategyDir interface{}) *Runtime_Run_Call {
	return &Runtime_Run_Call{Call: _e.mock.On("Run", strategyDir)}
}

func (_c *Runtime_Run_Call) Run(run func(strategyDir string)) *Runtime_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Runtime_Run_Call) Return(_a0 error) *Runtime_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Runtime_Run_Call) RunAndReturn(run func(string) error) *Runtime_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewRuntime creates a new instance of Runtime. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRuntime(t interface {
	mock.TestingT
	Cleanup(func())
}) *Runtime {
	mock := &Runtime{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
