// Code generated by mockery v2.53.5. DO NOT EDIT.

package live

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	os "os"
)

// SignalHandler is an autogenerated mock type for the SignalHandler type
type SignalHandler struct {
	mock.Mock
}

type SignalHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *SignalHandler) EXPECT() *SignalHandler_Expecter {
	return &SignalHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: ctx, onSignal
func (_m *SignalHandler) Handle(ctx context.Context, onSignal func(os.Signal) error) error {
	ret := _m.Called(ctx, onSignal)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(os.Signal) error) error); ok {
		r0 = rf(ctx, onSignal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SignalHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type SignalHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - onSignal func(os.Signal) error
func (_e *SignalHandler_Expecter) Handle(ctx interface{}, onSignal interface{}) *SignalHandler_Handle_Call {
	return &SignalHandler_Handle_Call{Call: _e.mock.On("Handle", ctx, onSignal)}
}

func (_c *SignalHandler_Handle_Call) Run(run func(ctx context.Context, onSignal func(os.Signal) error)) *SignalHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(os.Signal) error))
	})
	return _c
}

func (_c *SignalHandler_Handle_Call) Return(_a0 error) *SignalHandler_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SignalHandler_Handle_Call) RunAndReturn(run func(context.Context, func(os.Signal) error) error) *SignalHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewSignalHandler creates a new instance of SignalHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSignalHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *SignalHandler {
	mock := &SignalHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
