// Code generated by mockery v2.53.5. DO NOT EDIT.

package live

import (
	mock "github.com/stretchr/testify/mock"
	live "github.com/wisp-trading/wisp/pkg/live"
)

// StateStore is an autogenerated mock type for the StateStore type
type StateStore struct {
	mock.Mock
}

type StateStore_Expecter struct {
	mock *mock.Mock
}

func (_m *StateStore) EXPECT() *StateStore_Expecter {
	return &StateStore_Expecter{mock: &_m.Mock}
}

// GetPath provides a mock function with no fields
func (_m *StateStore) GetPath() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPath")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// StateStore_GetPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPath'
type StateStore_GetPath_Call struct {
	*mock.Call
}

// GetPath is a helper method to define mock.On call
func (_e *StateStore_Expecter) GetPath() *StateStore_GetPath_Call {
	return &StateStore_GetPath_Call{Call: _e.mock.On("GetPath")}
}

func (_c *StateStore_GetPath_Call) Run(run func()) *StateStore_GetPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StateStore_GetPath_Call) Return(_a0 string) *StateStore_GetPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateStore_GetPath_Call) RunAndReturn(run func() string) *StateStore_GetPath_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function with no fields
func (_m *StateStore) Load() ([]*live.Instance, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 []*live.Instance
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*live.Instance, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*live.Instance); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*live.Instance)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StateStore_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type StateStore_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *StateStore_Expecter) Load() *StateStore_Load_Call {
	return &StateStore_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *StateStore_Load_Call) Run(run func()) *StateStore_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StateStore_Load_Call) Return(_a0 []*live.Instance, _a1 error) *StateStore_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StateStore_Load_Call) RunAndReturn(run func() ([]*live.Instance, error)) *StateStore_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: instances
func (_m *StateStore) Save(instances []*live.Instance) error {
	ret := _m.Called(instances)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]*live.Instance) error); ok {
		r0 = rf(instances)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StateStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type StateStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - instances []*live.Instance
func (_e *StateStore_Expecter) Save(instances interface{}) *StateStore_Save_Call {
	return &StateStore_Save_Call{Call: _e.mock.On("Save", instances)}
}

func (_c *StateStore_Save_Call) Run(run func(instances []*live.Instance)) *StateStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]*live.Instance))
	})
	return _c
}

func (_c *StateStore_Save_Call) Return(_a0 error) *StateStore_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateStore_Save_Call) RunAndReturn(run func([]*live.Instance) error) *StateStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewStateStore creates a new instance of StateStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateStore {
	mock := &StateStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
