// Code generated by mockery v2.53.5. DO NOT EDIT.

package strategy

import mock "github.com/stretchr/testify/mock"

// CompileService is an autogenerated mock type for the CompileService type
type CompileService struct {
	mock.Mock
}

type CompileService_Expecter struct {
	mock *mock.Mock
}

func (_m *CompileService) EXPECT() *CompileService_Expecter {
	return &CompileService_Expecter{mock: &_m.Mock}
}

// CompileStrategy provides a mock function with given fields: strategyPath
func (_m *CompileService) CompileStrategy(strategyPath string) error {
	ret := _m.Called(strategyPath)

	if len(ret) == 0 {
		panic("no return value specified for CompileStrategy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(strategyPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CompileService_CompileStrategy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompileStrategy'
type CompileService_CompileStrategy_Call struct {
	*mock.Call
}

// CompileStrategy is a helper method to define mock.On call
//   - strategyPath string
func (_e *CompileService_Expecter) CompileStrategy(strategyPath interface{}) *CompileService_CompileStrategy_Call {
	return &CompileService_CompileStrategy_Call{Call: _e.mock.On("CompileStrategy", strategyPath)}
}

func (_c *CompileService_CompileStrategy_Call) Run(run func(strategyPath string)) *CompileService_CompileStrategy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *CompileService_CompileStrategy_Call) Return(_a0 error) *CompileService_CompileStrategy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CompileService_CompileStrategy_Call) RunAndReturn(run func(string) error) *CompileService_CompileStrategy_Call {
	_c.Call.Return(run)
	return _c
}

// IsCompiled provides a mock function with given fields: strategyPath
func (_m *CompileService) IsCompiled(strategyPath string) bool {
	ret := _m.Called(strategyPath)

	if len(ret) == 0 {
		panic("no return value specified for IsCompiled")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(strategyPath)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// CompileService_IsCompiled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsCompiled'
type CompileService_IsCompiled_Call struct {
	*mock.Call
}

// IsCompiled is a helper method to define mock.On call
//   - strategyPath string
func (_e *CompileService_Expecter) IsCompiled(strategyPath interface{}) *CompileService_IsCompiled_Call {
	return &CompileService_IsCompiled_Call{Call: _e.mock.On("IsCompiled", strategyPath)}
}

func (_c *CompileService_IsCompiled_Call) Run(run func(strategyPath string)) *CompileService_IsCompiled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *CompileService_IsCompiled_Call) Return(_a0 bool) *CompileService_IsCompiled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CompileService_IsCompiled_Call) RunAndReturn(run func(string) bool) *CompileService_IsCompiled_Call {
	_c.Call.Return(run)
	return _c
}

// NeedsRecompile provides a mock function with given fields: strategyPath
func (_m *CompileService) NeedsRecompile(strategyPath string) bool {
	ret := _m.Called(strategyPath)

	if len(ret) == 0 {
		panic("no return value specified for NeedsRecompile")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(strategyPath)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// CompileService_NeedsRecompile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NeedsRecompile'
type CompileService_NeedsRecompile_Call struct {
	*mock.Call
}

// NeedsRecompile is a helper method to define mock.On call
//   - strategyPath string
func (_e *CompileService_Expecter) NeedsRecompile(strategyPath interface{}) *CompileService_NeedsRecompile_Call {
	return &CompileService_NeedsRecompile_Call{Call: _e.mock.On("NeedsRecompile", strategyPath)}
}

func (_c *CompileService_NeedsRecompile_Call) Run(run func(strategyPath string)) *CompileService_NeedsRecompile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *CompileService_NeedsRecompile_Call) Return(_a0 bool) *CompileService_NeedsRecompile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CompileService_NeedsRecompile_Call) RunAndReturn(run func(string) bool) *CompileService_NeedsRecompile_Call {
	_c.Call.Return(run)
	return _c
}

// PreCompileStrategies provides a mock function with given fields: strategiesDir
func (_m *CompileService) PreCompileStrategies(strategiesDir string) map[string]error {
	ret := _m.Called(strategiesDir)

	if len(ret) == 0 {
		panic("no return value specified for PreCompileStrategies")
	}

	var r0 map[string]error
	if rf, ok := ret.Get(0).(func(string) map[string]error); ok {
		r0 = rf(strategiesDir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]error)
		}
	}

	return r0
}

// CompileService_PreCompileStrategies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreCompileStrategies'
type CompileService_PreCompileStrategies_Call struct {
	*mock.Call
}

// PreCompileStrategies is a helper method to define mock.On call
//   - strategiesDir string
func (_e *CompileService_Expecter) PreCompileStrategies(strategiesDir interface{}) *CompileService_PreCompileStrategies_Call {
	return &CompileService_PreCompileStrategies_Call{Call: _e.mock.On("PreCompileStrategies", strategiesDir)}
}

func (_c *CompileService_PreCompileStrategies_Call) Run(run func(strategiesDir string)) *CompileService_PreCompileStrategies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *CompileService_PreCompileStrategies_Call) Return(_a0 map[string]error) *CompileService_PreCompileStrategies_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CompileService_PreCompileStrategies_Call) RunAndReturn(run func(string) map[string]error) *CompileService_PreCompileStrategies_Call {
	_c.Call.Return(run)
	return _c
}

// NewCompileService creates a new instance of CompileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompileService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompileService {
	mock := &CompileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
